java -cp bin Project1 1 &
read -p "Press [Enter] to continue..."
java -cp bin Project1 2 &
read -p "Press [Enter] to continue..."
java -cp bin Project1 3 &
read -p "Press [Enter] to continue..."
java -cp bin Project1 4 &
read -p "Press [Enter] to continue..."
java -cp bin Project1 5 &
read -p "Press [Enter] to continue..."
java -cp bin Project1 6 &
read -p "Press [Enter] to continue..."
java -cp bin Project1 7 &
read -p "Press [Enter] to continue..."
java -cp bin Project1 8 &
read -p "Press [Enter] to continue..."
java -cp bin Project1 9 &
read -p "Press [Enter] to continue..."
java -cp bin Project1 10 &
